### ISSUE TITLE
Title not displaying correctly when uploading single paper to beta.ripeta.com front end.

### ISSUE THREAD

**Issue by ejcramer** [ripeta/general#1]
Issue submitted by elly and leah, see comment below

Links to ripeta/repeat-fore#24

**Comment by lhaynes2** [comment]
Beta ripeta title bug

When uploading articles to beta.ripeta, there is an issue with the title that doesn’t occur when uploading a document using the batch load but only when doing so individually.

Specifically, when uploading the papers PMC5707430 and PMC5704657 as a batch the titles appeared as J Med Internet Res. 2017 Nov; 19(11): e388 and PMC5704657 respectively. Neither of these extracted titles are correct but they were extracted from the correct article, so no problem with the batch upload.

However, when uploading the same paper (**PMC5704657**) individually, the title appears as something completely unrelated to the paper (Hepatitis C Screening: The Downstream Dissemination of Evolving Guidelines in a Resident Continuity Clinic) which is actually a separate paper with PMC5589512. 

The API Paper IDs 199 and 200 are the same paper with the former being uploaded by batch and the latter individually. The extracted variable results remain the same uploaded either way, however the titles differ.
Elly’s comment:  This sounds like a bug and I will attempt to reproduce it so I can fix it.  Your descriptions, actions, and screenshots are very helpful.  Thanks!

The title at the top of the research 
reproducibility report is extracted from the correct paper   
<img width="683" alt="screen shot 2018-08-01 at 8 06 08 pm" src="https://user-images.githubusercontent.com/35510486/43596562-3fa02d3c-9645-11e8-9f07-89f041c51e9b.png">
 
But when inputting variables manually
The title appears incorrectly again. (No mention of hepatitis is ever found in the original paper)

<img width="578" alt="screen shot 2018-08-01 at 8 05 51 pm" src="https://user-images.githubusercontent.com/35510486/43596563-3fb65666-9645-11e8-975f-6e7cfce2c98a.png">

**Comment by ejcramer** [comment]
Leah,

I made another fix related to the title not changing in the "ALL Papper" page after adding a user annotation in article_title.  Could you test that out again and see if it works for you now on http://beta.ripeta.com?

Thanks!

elly

**Comment by ejcramer** [comment]
Leah confirmed that the bug has been fixed.
