### ISSUE TITLE
Latest version of the data dictionary from research/science team

### ISSUE THREAD

**Issue by ejcramer** [ripeta/general#14]
Could you please find out what the latest data dictionary is that we/devs should use for reference.
Thank you!

**Comment by arham-saif** [comment]
I spoke with Anthony, and he said that the link below is the one that they want us to use for now, even though it is old. Moving forward, the research team will update the data dictionary. But for now, the link below should be the standard.

https://github.com/ripeta/Research_Reproducibility/blob/master/DataDictionary/RepeAT05_DataDictionary_2016-11-08.csv

**Comment by ejcramer** [comment]
That is what I have been using so that's gtk.  Thank you Arham!
