### ISSUE TITLE
On beta.ripeta.com, when closing the user input, return directly to the previous page with the popdown still open

### ISSUE THREAD

**Issue by lhaynes2** [ripeta/general#2]
When closing the user input page on beta.ripeta.com, it seems it would be more efficient for those submitting user input if, when closing the user input page, rather than returning to the overall reproducibility report and requiring one to reopen the previously opened pop-down, this pop-down would remain open when the user input page is closed.

This was noticed on beta.ripeta.com within the research reproducibility reports on a mac on safari on 08/10/18.

For example, if one is originally on this page...
<img width="1003" alt="screen shot 2018-08-14 at 1 26 04 pm" src="https://user-images.githubusercontent.com/35510486/44110550-a552e29e-9fc5-11e8-9e00-29398c1efb02.png">

and then goes to edit the user input...
<img width="990" alt="screen shot 2018-08-14 at 1 29 21 pm" src="https://user-images.githubusercontent.com/35510486/44110727-198e8c8a-9fc6-11e8-9701-dd01a4d54c43.png">

once you click the green "save" it returns to this page...
<img width="1122" alt="screen shot 2018-08-14 at 1 23 56 pm" src="https://user-images.githubusercontent.com/35510486/44110444-50c1edb0-9fc5-11e8-8b93-df37fe456de0.png">

However, it would be more convenient/efficient/aesthetic if it were to return to the page with the pop-down still open (as shown by the first screenshot) especially when one is inputting many variables at once or successively. It also may be interesting to note that when simply closing the user input page using the 'x' in the top right corner it does return to the page shown in the first screenshot.

**Comment by ejcramer** [comment]
Issue moved to [ripeta/repeat-fore #28](https://github.com/ripeta/repeat-fore/issues/28) via [**ZenHub**](https://www.zenhub.com/)
