### ISSUE TITLE
Structured Text Includes Editors, Reviewers Etc. as Authors

### ISSUE THREAD

**Issue by arham-saif** [ripeta/general#20]
### Author Names from Paper id 215
As we can see the actual list of authors for the paper are below:

![actual list of authors](https://user-images.githubusercontent.com/43044812/46786143-9ac00a80-ccf9-11e8-9c14-125ee6a29f2f.png)

Screenshots of all the places within the pdf where the authors are mentioned:

![extra authors not seen2](https://user-images.githubusercontent.com/43044812/46786250-f38fa300-ccf9-11e8-9a3d-a2b9e76ff39b.png)
![extra authors not seen1](https://user-images.githubusercontent.com/43044812/46786258-f68a9380-ccf9-11e8-9416-520ea54f0c10.png)

**But a very interesting phenomenon was found on the research reproducibility report, namely some extra authors appeared seemingly out of nowhere:**

![they are not the authors](https://user-images.githubusercontent.com/43044812/46786614-05257a80-ccfb-11e8-9a0b-81f6bdf60c57.png)

These extra people who happened to be the editor and reviewers were only found in one place within the pdf, that too their full names don't appear as well as not in the order shown in the research reproducibility report (last name, first name):

![only place extras are seen within pdf](https://user-images.githubusercontent.com/43044812/46786532-c8f21a00-ccfa-11e8-9fa8-a38e3900108c.png)

**_After some digging within the struct_text, I found them under the "contributor-list". Now obviously we cannot list the editor and reviewers as authors, and I wonder if its a one off or does many struct_text list the editor and and reviewers as the "contributors"? If so, how do we tackle this issue?_**

![where the names come from](https://user-images.githubusercontent.com/43044812/46786990-1d49c980-ccfc-11e8-901a-3f9ec23b6bc5.png)

**Comment by cmw48** [comment]
Sample XML from this paper below:    
xmltojson conversion should only include contrib-type = author and exclude editor, reviewer and any other types that exist in this tag.

 <contrib-group>
        <contrib contrib-type="editor">
          <name>
            <surname>Eysenbach</surname>
            <given-names>Gunther</given-names>
          </name>
        </contrib>
      </contrib-group>
      <contrib-group>
        <contrib contrib-type="reviewer">
          <name>
            <surname>Purkayastha</surname>
            <given-names>Saptarshi</given-names>
          </name>
        </contrib>
        <contrib contrib-type="reviewer">
          <name>
            <surname>Mircheva</surname>
            <given-names>Iskra</given-names>
          </name>
        </contrib>
      </contrib-group>
      <contrib-group>
        <contrib id="contrib1" contrib-type="author" corresp="yes">
          <name>
            <surname>Wellner</surname>
            <given-names>Ben</given-names>
          </name>
          <degrees>MSc, PhD</degrees>
          <xref ref-type="aff" rid="aff1">1</xref>
          <address>
            <institution>The MITRE Corporation</institution>
            <addr-line>202 Burlington Rd</addr-line>
            <addr-line>Bedford, MA, 01730</addr-line>
            <country>United States</country>
            <phone>+1 781 271 7191</phone>
            <fax>+1 781 271 2352</fax>
            <email>wellner@mitre.org</email>
          </address>
          <contrib-id contrib-id-type="orcid">http://orcid.org/0000-0003-2689-990X</contrib-id>
        </contrib>
        <contrib id="contrib2" contrib-type="author">

**Comment by ejcramer** [comment]
Issue moved to [ripeta/repeat-ingest #6](https://github.com/ripeta/repeat-ingest/issues/6) via [**ZenHub**](https://www.zenhub.com/)
