### ISSUE TITLE
Issue in extraction process when code is looking for the end of a sentence

### ISSUE THREAD

**Issue by lhaynes2** [ripeta/general#4]
Summarize issue

08/13/18 on safari on my mac

Describe whats wrong
<img width="941" alt="study_purpose sentence wrong" src="https://user-images.githubusercontent.com/35510486/44117202-36ff49dc-9fd8-11e8-87b7-350e7df96e47.png">

Describe what it should be

**Comment by ejcramer** [comment]
Issue moved to [ripeta/repeat-plugins #13](https://github.com/ripeta/repeat-plugins/issues/13) via [**ZenHub**](https://www.zenhub.com/)
