### ISSUE TITLE
Add journal title field to the framework on the data.ripeta.com site

### ISSUE THREAD

**Issue by cynhudson** [ripeta/general#5]

**Comment by ejcramer** [comment]
I believe the best plan for this is to create the journal title plugin and use that in the interface.  Journal title will also need to be searchable (future feature).

Issue copied to ripeta/repeat-plugins/#12

**Comment by ejcramer** [comment]
Issue moved to [ripeta/repeat-fore #29](https://github.com/ripeta/repeat-fore/issues/29) via [**ZenHub**](https://www.zenhub.com/)
