### ISSUE TITLE
Upload Error on Beta.Ripeta

### ISSUE THREAD

**Issue by arham-saif** [ripeta/general#7]
`file_get_contents(/var/www/html/beta/web/uploads/Large Genomic Fragment Deletions &amp; Instertions in Mouse Using CRISPR_Cas9(PLOS).PDF): failed to open stream: No such file or directory`

When uploading the paper "Large Genomic Fragment Deletions & Instertions in Mouse Using CRISPR/Cas9(PLOS)" this issue was found. The file uploads but when its ran through the API, the page crashes.

**Comment by ejcramer** [comment]
Issue moved to [ripeta/repeat-fore #26](https://github.com/ripeta/repeat-fore/issues/26) via [**ZenHub**](https://www.zenhub.com/)
