### ISSUE TITLE
Seems to extract the very first DOI it finds, without checking to see if its the correct DOI or not.

### ISSUE THREAD

**Issue by arham-saif** [ripeta/general#9]
The images below depict how parsing through a pdf our current plugins extract the very first DOI it comes across, without verifying whether that's the correct DOI or not. In the example below the very first DOI it captured was from the previous paper while the actual DOI of the article is at the very bottom of the article.

![captures doi from the top of paper 2](https://user-images.githubusercontent.com/43044812/45383557-32ceb500-b5d1-11e8-8324-73e1a6aa630e.jpg)
![correct doi at the end of paper 2](https://user-images.githubusercontent.com/43044812/45383562-36fad280-b5d1-11e8-8897-d64e617fb8d6.jpg)

**Comment by ejcramer** [comment]
Issue moved to [ripeta/repeat-plugins #15](https://github.com/ripeta/repeat-plugins/issues/15) via [**ZenHub**](https://www.zenhub.com/)
